version: '3.1'
services:
  airport-reservation-system:
    image: airport-reservation-appl
    build: ./
    ports:
      - "8085:8085"
    restart: always
    depends_on:
      - postgres-db
#      - rabbitmq
#      - zookeeper
    links:
      - postgres-db
#      - rabbitmq
#      - zookeeper

  postgres-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=patika_airport_reservation_system_db

#  rabbitmq:
#    image: rabbitmq:3.8.3-management
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"

#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    restart: always
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    restart: always
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#    depends_on:
#      - zookeeper
#    links:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092